"""Long-form story copy for each product page. Voice: we. No em-dashes. Only facts we can stand behind.
Each story: headline, dek, caption, body = list of ("p", text) | ("h", subhead) | ("q", pull quote)."""
STORIES = {
"aviator-iq": dict(
 headline="Learning to fly starts on the ground. We built a calmer place to do it.",
 dek="Aviator IQ covers the FAA's knowledge tests, from Private Pilot to ATP, and ties every question back to the handbook it came from.",
 caption="Aviator IQ, the place we built to study for the FAA knowledge tests.",
 body=[
  ("p","Ask almost any pilot about ground school and you will hear the same story: enormous handbooks, charts that look like riddles, and practice tools that seem to have been designed in 2004. The knowledge test is a real hurdle, and for years the way to prepare for it has been to endure it."),
  ("p","We thought that was a fixable problem. Aviator IQ is our answer: one place to study for thirteen FAA knowledge exams, from Private Pilot all the way up to Airline Transport Pilot, built to feel as calm as the cabin of a well-flown airplane."),
  ("h","Every answer has an address"),
  ("p","The principle behind the product is simple. A question is only useful if you can see where it came from. So each one is mapped to the source it is drawn from: the FAA's own handbooks, the Airman Certification Standards, and the official testing figures. When you get something wrong, the explanation points you back to the chapter, so a single missed question becomes a single solid lesson."),
  ("q","A missed question should turn into a lesson, not a reason to memorize and move on."),
  ("p","The figures matter more than people expect. On test day you are handed charts and supplements, and reading them quickly is a skill of its own. In Aviator IQ those figures sit right beside the question, the way they will in the testing room."),
  ("h","Knowing when you are ready"),
  ("p","Most students book their test on a hunch. We wanted to replace the hunch with something honest, so Aviator IQ gives you a readiness score that blends how much of the material you have covered, how accurate you are, how well you remember it, and how quickly you answer. It moves when you learn. It does not flatter you."),
  ("p","You can study the way your week allows: a quick set on a lunch break, a drill on one weak topic, or a full simulator run when you want to find out how exam day would go."),
  ("h","More than a question bank"),
  ("p","Around the practice sits a growing library of study guides, a tool for looking up the codes on your test results, and an index of pass rates built from real FAA data. It is written for the student pilot working toward a first certificate, the instructor refreshing a lesson, and the airline hopeful with a long road ahead."),
  ("p","Aviator IQ is on the web, and it is now in the App Store for iPhone and iPad and on Google Play for Android, so a quick drill can happen anywhere you have a few minutes."),
  ('h','Who it is for'),
  ('p','Aviator IQ is for anyone with an FAA knowledge test ahead of them: student pilots working toward a first certificate, instrument and commercial candidates, aspiring flight and ground instructors, aircraft mechanics, and remote pilots getting ready for the Part 107 drone exam.'),
  ('h','What is inside'),
  ('p','Thirteen exams in all: Private Pilot, Sport Pilot, Instrument, Commercial and Airline Transport Pilot; Flight Instructor, Instrument Flight Instructor, Fundamentals of Instructing and Ground Instructor; Mechanic General, Airframe and Powerplant; and Remote Pilot for small drones. Each exam has its own question bank, practice runs and a full simulator, matched to the real test. The Private Pilot test, for example, is 60 questions with a 70 percent passing score, and the bank behind it holds 985 questions.'),
 ]),
"citizen-pass": dict(
 headline="Becoming a citizen is one of life's biggest days. The study material should not be a PDF.",
 dek="Citizen Pass turns official study material into quizzes, mock exams and a readiness score, for the United States, the United Kingdom, Canada and Australia.",
 caption="Citizen Pass, our home for citizenship test practice.",
 body=[
  ("p","The citizenship test is a short exam with a long shadow. For many people it marks the end of years of paperwork, waiting and uncertainty, and the preparation they are offered is often a government PDF and a prayer."),
  ("p","Citizen Pass takes that official study material and turns it into something you can actually practice with: quizzes, full mock exams, and a single honest Readiness Score that tells you when to stop worrying and book the date."),
  ("h","One pass, four countries"),
  ("p","We built it for the United States, the United Kingdom, Canada and Australia. Each country has its own test, its own handbook and its own quirks, so each gets its own content rather than one generic quiz with the flags swapped. What stays the same is the approach: start from the official source, explain every answer in plain language, and measure readiness by what you have actually learned."),
  ("h","In the language you think in"),
  ("p","A test about a country's history and values should not also be a test of how comfortable you are with English. The study site comes in Spanish, French, Chinese, Korean and Vietnamese as well as English, because good preparation should not depend on which language you grew up speaking."),
  ("q","Good preparation should not depend on the language you grew up speaking."),
  ("h","A score you can trust"),
  ("p","The Readiness Score is the part we are proudest of. It reflects mastery, not how many flash cards you flipped. It rises when you understand something and falls when you do not, which is exactly why it is useful."),
  ("h","Beyond the test"),
  ("p","For Canada we also built a stage-by-stage timeline of the whole path to citizenship, with a library of the questions people ask along the way. And because applicants spend so much time waiting, we publish open data pages on processing times and trends, built from public sources."),
  ('h','Who it is for'),
  ('p','Citizen Pass is for permanent residents getting ready to naturalize, and for the family members helping them study. It is written for people who may be taking the test in a second language, often while working and raising a family.'),
  ('h','What is inside'),
  ('p',"Each country has its own practice. The United States civics test has 128 official questions, Canada's citizenship test has 596 questions, Australia's has 429, and the Life in the UK test has 180. Every one comes with mock exams, plain-language explanations and a readiness score, built from that country's own official study guide."),
 ]),
"dmv-iq": dict(
 headline="Fifty-one driving tests, and no two of them are quite the same.",
 dek="DMV IQ is built state by state, so you practice the rules of the place where you will actually take the test.",
 caption="DMV IQ, practice built around each state's own rules.",
 body=[
  ("p","There is no national driving test. Every state, and the District of Columbia, writes its own rulebook, sets its own passing score and asks its own questions. The pattern most prep tools follow is to ignore that, hand everyone the same generic quiz, and hope the overlap is big enough."),
  ("p","We started from the opposite end. DMV IQ holds more than 7,500 practice questions across all fifty states and DC, and the details that differ from one state to the next are checked against each state's own material."),
  ("q","A permit test should be about the rules of your state, not anyone else's."),
  ("h","Signs first, then the road"),
  ("p","Road signs are where many people lose easy points, so the app trains them visually: shapes, colors and meanings that stick through repetition rather than memorization. When the written test is behind you, step-by-step road test guides cover the part of the process that comes next."),
  ("h","Studying where it counts"),
  ("p","Not all study time is equal. DMV IQ shows how ready you are as a simple percentage, then points you at the questions you are most likely to miss, so the hours you have go where they matter. Personalized study puts your weak spots first."),
  ('h','Who it is for'),
  ('p',"DMV IQ is for first-time drivers and teenagers working toward a learner's permit, new arrivals to the United States who need a state licence, adults returning to the road, and professionals preparing for a commercial driver's licence."),
  ('h','What is inside'),
  ('p','Three kinds of practice for all fifty states and the District of Columbia: car, motorcycle and CDL. In total there are more than 7,500 questions, built from 51 official state handbooks. The car permit test alone has more than 3,000 questions across 13 categories, and the motorcycle test has more than 1,600 across seven. States set their own rules for the written test, and most use between 20 and 50 questions with a passing score between 70 and 80 percent, so each state has its own set.'),
  ('p','Alongside the practice sits a library of guides: road signs, what to bring to the DMV, how many times you can retake the test, and state-by-state comparisons such as the cost of becoming a driver and the share of uninsured drivers.'),
 ]),
"drive-iq-canada": dict(
 headline="Canada has no single driving test, so we wrote prep for every one of them.",
 dek="Drive IQ Canada covers G1, SAAQ, ICBC, Class 7 and every province, in English and in French.",
 caption="Drive IQ Canada, built province by province.",
 body=[
  ("p","Learning to drive in Canada means learning a different handbook depending on where you live. Ontario's G1, Quebec's SAAQ exam, British Columbia's ICBC knowledge test and a long list of others share a purpose and almost nothing else."),
  ("p","Drive IQ Canada is built province by province and territory by territory. A question about speed zones in Quebec is checked against Quebec's own handbook, not borrowed from somewhere else, and answers are verified against the official material of the province they belong to."),
  ("h","Written for Quebec, not just translated for it"),
  ("p","The app is fully bilingual. That is easy to say and hard to do well: a translated question can quietly stop matching the rule it was meant to test. So the French content is written and checked on its own terms, against the SAAQ's wording rather than an English original."),
  ("q","A translated question can quietly stop matching the rule it was meant to test."),
  ("h","Beyond the family car"),
  ("p","Passenger cars are only part of the story. Drive IQ Canada also covers motorcycles and the commercial classes, so the person preparing for a Class 1 gets the same care as the person preparing for a first licence."),
  ("h","An index that says when it does not know"),
  ("p","We publish a Driving Index that compares provinces using real data. Where a province does not have enough information to rank fairly, we leave it unranked instead of inventing a number. We would rather be honest than tidy."),
  ('h','Who it is for'),
  ('p',"Drive IQ Canada is for new drivers working toward a G1, a Quebec learner's licence or the equivalent in their province, newcomers exchanging a foreign licence, motorcyclists, and people preparing for commercial classes. It works for English and French speakers alike."),
  ('h','What is inside'),
  ('p',"Practice for all thirteen provinces and territories, in English and in French. Cars and light trucks have more than 2,500 questions, motorcycles more than 1,900, and there is a separate commercial track for every province and territory, plus a road signs trainer. Each province's questions come from its own official handbook, so what you study is what your province actually tests."),
 ]),
"insurance-pass": dict(
 headline="Insurance exams test the law, so we put the law on every answer.",
 dek="Insurance Pass prepares future producers and adjusters for their state licensing exams, with the statute behind each answer.",
 caption="Insurance Pass, practice built on each state's law.",
 body=[
  ("p","An insurance licence exam looks like a test of vocabulary and turns out to be a test of law. What counts as a covered loss, who can sell what, how a claim must be handled: the answers live in statutes and regulations, and those change when you cross a state line."),
  ("p","Most prep tools wave in that direction. We went and read the law."),
  ("h","Four lines of authority"),
  ("p","Insurance Pass covers four lines of authority: Life and Health, Property and Casualty, Personal Lines, and Adjuster. You pick your state, pick your line, and practice what your exam actually covers, across the states and the District of Columbia."),
  ("h","Every answer shows its source"),
  ("p","Questions are built from state statutes and regulations, and each answer quotes the provision behind it. That changes how studying feels. Instead of memorizing a result, you see the sentence of law that produces it, which is exactly what you need when the exam rewords the question."),
  ("q","Instead of memorizing a result, you see the sentence of law that produces it."),
  ("h","Treated like a future professional"),
  ("p","People taking these exams are about to be licensed to give advice that affects other people's money and safety. The preparation should respect that. There are no trick questions and no hand-waving, just the rule and the reason it is the rule, and a readiness score that tells you when you are set for the proctor."),
  ('h','Who it is for'),
  ('p','Insurance Pass is for people entering the insurance business: new agents and producers sitting a state licensing exam, professionals adding a second line, and claims adjusters who need their own licence.'),
  ('h','What is inside'),
  ('p',"Four lines of authority. Life and Health and Property and Casualty are covered in all 50 states and the District of Columbia, Personal Lines in 44 states, and Claims Adjuster in the states that require its own exam. Every question is built from your state's statutes and regulations, and each answer shows the provision behind it."),
 ]),
"airwaves-iq": dict(
 headline="Radio licences, explained one worked problem at a time.",
 dek="Airwaves IQ prepares students for the Technician, General and Extra exams and the FCC's commercial licences, using the official question pools.",
 caption="Airwaves IQ, a study room for radio licences.",
 body=[
  ("p","Radio exams are a pleasure if you love electronics and a headache if you only want the licence. Airwaves IQ is built for both kinds of people, and for the large group in between who are not sure yet which kind they are."),
  ("p","It covers nine FCC exams: the amateur Technician, General and Extra classes, and commercial licences including the GROL, radar and GMDSS. Practice comes from the current official question pools, so what you work on is what the exam draws from."),
  ("h","The math, shown"),
  ("p","Formulas stop being magic when you can watch them work. Every calculation question comes with a worked derivation, step by step, so you learn how to get the answer instead of memorizing what it was."),
  ("q","Formulas stop being magic when you can watch them work."),
  ("h","Where the rules live"),
  ("p","Regulatory questions can feel arbitrary until you know where the rule comes from. Each explanation points to the section of the regulations it rests on, so you learn where to look as well as what to answer. Schematics appear where the real test puts them, and you can work through the syllabus topic by topic, ticking off what you have covered."),
  ("h","Knowing when to book the session"),
  ("p","A readiness score tracks how prepared you are, so you can aim for it before you go find a volunteer exam session. It works well in a phone's browser."),
  ('h','Who it is for'),
  ('p','Airwaves IQ is for people earning their first amateur radio licence, hams moving up to General or Extra, and professionals who need an FCC commercial licence for maritime, aviation or broadcast work. Amateur and commercial licences are federal, so one licence is valid in every state and US territory.'),
  ('h','What is inside'),
  ('p','Nine exams across two families. On the amateur side are the Technician, General and Extra classes, with 1,431 questions between them, each with worked derivations. On the commercial side are the General Radiotelephone licence, Marine Radio Law, GMDSS operating practices, GMDSS radio maintenance and ship radar. The Technician exam, for instance, is 35 questions with a 74 percent passing score.'),
 ]),
"mariner-iq": dict(
 headline="A captain's licence is a serious goal. The preparation should be calm.",
 dek="Mariner IQ uses the Coast Guard's own sample exams, with a plain-English explanation on every answer.",
 caption="Mariner IQ, calm preparation for Coast Guard licence exams.",
 body=[
  ("p","Earning a captain's licence is one of those goals people work toward for years. The prep options, on the other hand, can feel like a flea market: scattered, uneven, and rarely clear about where their questions came from."),
  ("p","Mariner IQ is the calmer alternative. It is built from the Coast Guard's own sample exams, covering credentials from the six-pack and the 100-ton master to able seaman and more."),
  ("h","The source is the Coast Guard"),
  ("p","We start from what the Coast Guard publishes and keep every official question exactly as written, with the official answer. Nothing is reworded to make it easier or to make it ours."),
  ("h","Plain English at sea"),
  ("p","Maritime language is dense on purpose, and it is easy to nod along without really understanding it. Every answer in Mariner IQ comes with an explanation in plain English, so the rules of the road and the logic of navigation make sense the first time you read them."),
  ("q","Maritime language is dense on purpose. The explanation should not be."),
  ("h","Made for the wheelhouse"),
  ("p","There is even a bridge-red night mode, a screen that keeps your night vision intact for study sessions on the water after dark."),
  ('h','Who it is for'),
  ('p','Mariner IQ is for people taking a Coast Guard licence exam: charter and fishing captains going for their first six-pack licence, mariners upgrading to a 100-ton master, deck officers and towing vessel mates, and the engineers, able seamen and lifeboatmen who keep vessels moving.'),
  ('h','What is inside'),
  ('p','Seventeen exams, from the six-pack and 100-ton master to towing vessel master, designated duty engineer and the QMED ratings. Question banks are large: the six-pack exam is 160 questions on test day, the 100-ton master exam is 210, and towing vessel master and mate is 260. Every exam has a 70 percent passing score and its own timed practice test.'),
 ]),
}
